<div class="footer_backtop">
  <span class="back_top" id="back_top">TOPへ戻る</span>
</div>
<div class="row">
  <a href="/">
    <picture>
      <source media="(max-width: 768px)" srcset="/common/images/logo_ft_sp.png" />
      <img src="/common/images/logo_ft_pc.png" alt="京都リフォーム ハウスウィンドウ" />
    </picture>
  </a>
  <div class="footer_link">
    <ul>
      <li><a href="">ホーム</a></li>
      <li><a href="/service">リフォームサービス紹介</a></li>
      <li><a href="/work">リフォーム施工事例</a></li>
      <li><a href="/company">会社案内</a></li>
      <li><a href="/privacy">プライバシーポリシー</a></li>
      <li><a href="/sitemap">サイトマップ</a></li>
    </ul>
    <div class="footer_contact">
      <a href="/contact" class="btn_top"><span>お問い合わせ</span></a>
      <div class="footer_contact_tel">
        <a href="tel:0120-88-1615" class="tel">0120-88-1615</a>
        <p>受付時間/<span>10:00–18:00</span></p>
      </div>
    </div>　
  </div>
  <p class="footer_copyright">Copyright©株式会社ハウスウィンドウ. All rights reserved.</p>
</div>