<div class="header_top show_pc">
  <div class="row">
    <a href="/sitemap" class="header_top_btn">サイトマップ</a>
  </div>
</div>
<div class="header_mid row">
  <h1 class="header_mid_logo">
    <a href="/">
      <picture>
        <source media="(max-width: 768px)" srcset="/common/images/logo_sp.png" />
        <img src="/common/images/logo_pc.png" alt="リフォーム専門店株式会社ハウスウィンドウ" />
      </picture>
    </a>
  </h1>
  <p>京都のリフォーム専門店ハウスウィンドウ</p>
  <div class="header_mid_listlink show_pc" id="header_mid_listlink">
    <ul>
      <li>
        <a href="#reform_store" class="js_archorlink">
          <p>
            <span>HOME STYLE RENOVATION</span>
            <small>京都市伏見区下鳥羽西芹川町52</small>
          </p>
          <span>アクセス</span>
        </a>
      </li>
      <li>
        <a href="#reform_store" class="js_archorlink">
          <p>
            <span>向日市ステーションパーク店</span>
            <small>京都府向日市鶏冠井町西金村5</small>
          </p>
          <span>アクセス</span>
        </a>
      </li>
    </ul>
    <a href="/contact" class="btn_top show_sp"><span>お問い合わせ</span></a>
    <div class="header_mid_tel">
      <a href="tel:0120-88-1615" class="tel">0120-88-1615</a>
      <p>受付時間/<span>10:00–18:00</span></p>
    </div>
  </div>
  <div class="menu_icon_wr show_sp">
    <span class="menu_icon" id="menu_icon"></span>
    <i>メニュー</i>
  </div>
</div>
<div class="header_nav row" id="header_nav">
  <nav class="menu" id="menu">
    <ul>
      <li><a href="/">ホーム</a></li>
      <li><a href="/service">リフォームサービス紹介</a></li>
      <li><a href="/work">リフォーム施工事例</a></li>
      <li><a href="/company">会社案内</a></li>
      <li class="show_pc"><a href="/contact" class="btn_top"><span>お問い合わせ</span></a></li>
      <li class="show_sp"><a href="">プライバシーポリシー</a></li>
      <li class="show_sp"><a href="">サイトマップ</a></li>
    </ul>　　　 　　　 　　　
  </nav>
</div>